image: rocker/verse:4.1.0

stages:
  - renv
  - build
  - test
  - deploy

variables:
  RENV_CONFIG_REPOS_OVERRIDE: "http://cran.r-project.org"
  RENV_PATHS_CACHE: ${CI_PROJECT_DIR}/cache
  RENV_PATHS_LIBRARY: ${CI_PROJECT_DIR}/renv/library

cache:
  key: one-key-to-rule-them-all
  paths:
    - ${RENV_PATHS_CACHE}
    - ${RENV_PATHS_LIBRARY}

before_script:
  - Rscript -e "if (!requireNamespace('renv', quietly = TRUE)) install.packages('renv')"
  - Rscript -e "renv::restore()"

renv_setup:
  stage: renv
  script:
    - echo "Nothing to do..."

building:
  stage: build
  script:
    - R -e 'devtools::check(error_on = "error")'

# To have the coverage percentage appear as a gitlab badge follow these
# instructions:
# https://docs.gitlab.com/ee/user/project/pipelines/settings.html#test-coverage-parsing
# The coverage parsing string is
# Coverage: \d+\.\d+

testing:
    stage: test
    allow_failure: true
    when: on_success
    only:
        - master
    script:
        - Rscript -e 'covr::gitlab(file = "coverage/coverage.html", quiet = FALSE)'
    coverage: '/Coverage: \d+\.\d+/'
    artifacts:
        paths:
            - coverage

# To produce a code coverage report as a GitLab page see
# https://about.gitlab.com/2016/11/03/publish-code-coverage-report-with-gitlab-pages/

pages:
    stage: deploy
    dependencies:
        - testing
    script:
        - Rscript -e 'pkgdown::build_site()'
        - mv coverage public
    artifacts:
        paths:
            - public
        expire_in: 30 days
    only:
        - master
